language: python
python:
  - "3.10"

install:
  - pip install --upgrade pip
  - pip install flake8 pytest
  - pip install -r requirements_clean.txt
  - pip install -e .

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - pytest -q
