version: "3.9"

services:
  transcriberapp:
    container_name: transcriberapp
    build:
      context: .
      dockerfile: Dockerfile
    image: transcriberapp-container
    restart: unless-stopped

    # Necesario para Jetson (GPU)
    runtime: nvidia

    # Red local del host (para acceder desde fuera)
    network_mode: host

    # Montar el proyecto para desarrollo en vivo
    volumes:
      - .:/app

    # Memoria compartida para evitar errores de PyAV / FFmpeg
    shm_size: "8g"

    environment:
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1

    command: >
      uvicorn transcriber_app.web.web_app:app
      --host 0.0.0.0
      --port 9000
      --log-level debug
