apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: transcriberapp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`transcribeapp.felixmurcia.com`)
      kind: Rule
      services:
        - name: transcriberapp
          port: 80
  tls:
    certResolver: myresolver
